/* Copyright 2026 The OpenXLA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#include "absl/base/casts.h"
#include "third_party/nccl/nccl.h"
#include "xla/stream_executor/cuda/cuda_platform_id.h"
#include "xla/stream_executor/gpu/gpu_kernel_registry.h"
#include "xla/stream_executor/gpu/ragged_all_to_all_device_kernel.h"
#include "xla/stream_executor/gpu/ragged_all_to_all_device_kernel_lib.cu.h"

#define SINGLE_ARG(...) __VA_ARGS__

#define REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(VECTOR_SIZE, THREADS, POLICY)     \
  GPU_KERNEL_REGISTRY_REGISTER_KERNEL_STATICALLY(                                  \
      RaggedAllToAllDeviceKernelCuda##VECTOR_SIZE##Bytes##THREADS##Policy##POLICY, \
      SINGLE_ARG(                                                                  \
          stream_executor::gpu::RaggedAllToAllDeviceKernel<VECTOR_SIZE,            \
                                                           THREADS, POLICY>),      \
      stream_executor::cuda::kCudaPlatformId, ([](size_t arity) {                  \
        return stream_executor::KernelLoaderSpec::CreateInProcessSymbolSpec(       \
            absl::bit_cast<void*>(&SINGLE_ARG(                                     \
                stream_executor::gpu::RaggedAllToAllDeviceKernelImpl<              \
                    VECTOR_SIZE, THREADS, POLICY>)),                               \
            "ragged_all_to_all_device_kernel_" #VECTOR_SIZE "_bytes_" #THREADS     \
            "_threads_policy_" #POLICY,                                            \
            arity);                                                                \
      }));

REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 0);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 1);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 2);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 3);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 4);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 5);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 6);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 7);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 8);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 9);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 10);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 11);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 12);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 128, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 128, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 128, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 128, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 128, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 256, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 256, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 256, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 256, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 256, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(1, 512, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(2, 512, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(4, 512, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(8, 512, 13);
REGISTER_RAGGED_ALL_TO_ALL_DEVICE_KERNEL(16, 512, 13);
